name: Apple Silicon CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Create Build Directory
      run: mkdir -p build
      
    - name: Configure CMake
      working-directory: ./build
      run: cmake ..

    - name: Build
      working-directory: ./build
      run: cmake --build .
      
    - name: List Build Artifacts
      working-directory: ./build
      run: |
        echo "Contents of build directory:"
        find . -type f -name "test_*" -perm +111
        
    - name: Run Tests
      working-directory: ./build
      run: |
        # Find and run the test executables, wherever they are
        for test in $(find . -type f -name "test_*" -perm +111); do
          echo "Running test: $test"
          $test
        done
        
        # Alternatively, use CTest if tests are configured properly
        ctest --output-on-failure
